stages:
  - build

build:
  stage: build
  tags:
    - shell
  script:
    - docker build -t dataviz .
    - docker tag dataviz registry.njsm.de/mt/dataviz:latest
    - docker push registry.njsm.de/mt/dataviz:latest
